#!/bin/bash
# ---------------------------------------------------------------------------
# The history of this script is in git repo 
#
#     git@github.com:ORNL-TechInt/esgf-ornl-util.git
#
# ---------------------------------------------------------------------------
PIDS=`ps -ef | grep -v grep | grep -- "globus-gridftp-server" \
     | awk '{ printf "%s ", $2; }'`
echo $PIDS
if [[ "$PIDS" != "" ]]; then
    kill -9 $PIDS
fi

. /etc/esg.env
export X509_CERT_DIR=/etc/grid-security/certificates
export GLOBUS_TCP_PORT_RANGE=50000,51000
export GLOBUS_TCP_SOURCE_RANGE=50000,51000
export GSI_AUTHZ_CONF=/etc/grid-security/gsi-authz.conf
export GLOBUS_USAGE_DEBUG=MESSAGES,/esg/log/esg-server-usage-gridftp.log

# export GLOBUS_GSI_AUTHZ_DEBUG_LEVEL=2
# export GLOBUS_GSI_AUTHZ_DEBUG_FILE=/tmp/GFTPAUTHLOG
export JAVA_HOME=/usr/local/java

export LOGFILE=/var/log/gridftp-esg
echo "* * * Restarting servers at `date \"+%Y.%m%d %H:%M:%S\"`" >> $LOGFILE

# CHROOT="-chroot-path /lustre/esgfs"
# CHROOT="-chroot-path /esg/gridftp_root"

echo "CHROOT: '$CHROOT'"

CMD="/usr/local/globus/sbin/globus-gridftp-server \
    -no-cas $CHROOT -d ALL -l $LOGFILE"

nohup $CMD -p 2811 >> $LOGFILE 2>&1 &

nohup $CMD -p 2812 >> $LOGFILE 2>&1 &
